export const STRATEGY_DEFINITIONS = [
  {
    id: 'bullish-bat-core',
    name: 'Bullish Bat Core',
    description: 'Balanced bullish reversal cohort with mid-confidence Bat structure.',
    thesis: 'Useful baseline for clean bullish reversals without pushing too far into tiny samples.',
    harmonicType: 'Bat',
    market: 'Bullish',
    bin: '50-60',
  },
  {
    id: 'bearish-bat-pressure',
    name: 'Bearish Bat Pressure',
    description: 'Mirror Bat cohort for downside setups with the same confidence band.',
    thesis: 'Good counterweight to the bullish Bat profile when the market turns lower.',
    harmonicType: 'Bat',
    market: 'Bearish',
    bin: '50-60',
  },
  {
    id: 'bullish-gartley-continuation',
    name: 'Bullish Gartley Continuation',
    description: 'Bullish Gartley setups centered in the strongest common accuracy pocket.',
    thesis: 'A steadier continuation-style strategy candidate when Bat is too broad.',
    harmonicType: 'Gartley',
    market: 'Bullish',
    bin: '50-60',
  },
  {
    id: 'bearish-butterfly-reversal',
    name: 'Bearish Butterfly Reversal',
    description: 'Bearish Butterfly cohort for sharper downside reversals.',
    thesis: 'Lets us compare a more aggressive reversal structure against the core Bat ideas.',
    harmonicType: 'Butterfly',
    market: 'Bearish',
    bin: '50-60',
  },
  {
    id: 'bullish-shark-pressure',
    name: 'Bullish Shark Pressure',
    description: 'Bullish Shark setups inside the high-traffic mid-accuracy bucket.',
    thesis: 'Adds a less traditional harmonic family so the station is not just Bat/Gartley.',
    harmonicType: 'Shark',
    market: 'Bullish',
    bin: '50-60',
  },
  {
    id: 'bearish-crab-expansion',
    name: 'Bearish Crab Expansion',
    description: 'Bearish Crab cohort intended to capture wider downside stretch patterns.',
    thesis: 'Useful for seeing whether broader extension structures hold up historically.',
    harmonicType: 'Crab',
    market: 'Bearish',
    bin: '50-60',
  },
];
